### ISSUE TITLE
PROCEDURA DI ATTUAZIONE: SEZIONE "MOTIVO DEL RECLAMO" (UTENTE ANONIMO)

### ISSUE THREAD

**Issue by eborzacchi** [AgID/agid-forms-frontend#63]
## Comportamento atteso
Il pulsante "Scegli file" mi deve consentire di selezionare i file da allegare.

## Comportamento attuale
Errore: Il pulsante "Scegli file" non funziona:
	- su Google Chrome: non si apre il pop-up e non permette di selezionare nessun file
	- su Explorer: il pulsante non è cliccabile, non è possibile selezionare nessun file
	- su Firefox: il pulsante non è cliccabile, non è possibile selezionare nessun file

## Contesto
TEST SUI SEGUENTI BROWSER: 
A) Google Chrome V. 79.0.3945.130 (Build ufficiale) (a 64 bit)
B) Internet Explorer V. 11.864.17763.0
C) Firefox V. 72.0.2 (64 bit)

**Comment by pdavide** [comment]
Al momento non riesco a riprodurre il bug.
Dal mio browser funziona correttamente.
Questa mattina ho fixato un errore di configurazione, quindi è possibile che il problema adesso sia stato risolto.
Potresti effettuare un nuovo test e darmi un feedback?

**Comment by eborzacchi** [comment]
Ho ripetuto il test con i browser indicati e ti confermo che i pulsanti non si abilitano per selezionare un file.

**Comment by pdavide** [comment]
@eborzacchi ti riferisci al fatto che il bottone è disabilitato o che funziona?
Il fatto che sia disabilitato è normale perché non permette di caricare file agli utenti che non hanno verificato il loro indirizzo email. Il bottone infatti si abilita automaticamente dopo la verifica dell'indirizzo email.
Se il problema è questo probabilmente non è chiaro per l'utente, quindi possiamo provvedere a mettere una breve spiegazione.
Attendo tuo feedback.

**Comment by eborzacchi** [comment]
Si esatto, era questo il problema, dopo la verifica email i pulsanti si abilitano tutti. 
E' meglio mettere una spiegazione, perché non è chiaro che l'utente deve obbligatoriamente fare la verifica della mail, e che solo così poi si abilitano i pulsanti per gli allegati.

**Comment by pdavide** [comment]
Ok allora chiudo questa issue in favore della #67.
