### ISSUE TITLE
PROCEDURA DI ATTUAZIONE: SEZIONE "RISPOSTA DEL SOGGETTO EROGATORE" (UTENTE ANONIMO)

### ISSUE THREAD

**Issue by eborzacchi** [AgID/agid-forms-frontend#64]
## Comportamento atteso
Il pulsante "Scegli file" mi deve consentire di selezionare i file da allegare.

## Comportamento attuale
Il pulsante "Scegli file" non funziona:
	- su Google Chrome: non si apre il pop-up e non permette di selezionare nessun file 
	- su Explorer: il pulsante non è cliccabile, non è possibile selezionare nessun file
	- su Firefox: il pulsante non è cliccabile, non è possibile selezionare nessun file

## Contesto
TEST SUI SEGUENTI BROWSER: 
A) Google Chrome V. 79.0.3945.130 (Build ufficiale) (a 64 bit)
B) Internet Explorer V. 11.864.17763.0
C) Firefox V. 72.0.2 (64 bit)

**Comment by pdavide** [comment]
Vedi https://github.com/AgID/agid-forms-frontend/issues/63#issuecomment-582384917.

**Comment by eborzacchi** [comment]
Ho ripetuto il test e ti confermo che i pulsanti non si abilitano per selezionare un file.

**Comment by pdavide** [comment]
Vedi https://github.com/AgID/agid-forms-frontend/issues/63#issuecomment-582409334.

**Comment by pdavide** [comment]
Chiudo questa issue in favore della #67.
