### ISSUE TITLE
PROCEDURA DI ATTUAZIONE: "INVIO" (UTENTE ANONIMO)

### ISSUE THREAD

**Issue by eborzacchi** [AgID/agid-forms-frontend#66]
## Comportamento atteso
Sia la procedura di attuazione che quella del meccanismo di feedback devono presentare all’invio della segnalazione una notifica immediata:

1.	All’invio della segnalazione al protocollo (con mittente "EMAIL SEGNALANTE"), la proceduta invia automaticamente: 
        A) una email di avvenuta ricezione al segnalante
        B) una email all'Ufficio Protocollo AGID con mittente "EMAIL SEGNALANTE"

2.	Una volta protocollata (manualmente dall’ufficio) partirà una seconda notifica al mittente <EMAIL SEGNALANTE> di avvenuta protocollazione.

## Comportamento attuale
Non è possibile effettuare il TEST su "INVIA" la segnalazione, il sistema non lo consente poiché manca l'allegato (il pulsante allega file non ha funzionato). 
Pertanto il form non consente di inviare la segnalazione e restituisce il messaggio:
	- assicurati di aver corretto tutti gli errori ed aver compilato tutti i campi obbligatori prima di salvare il modulo verifica l'indirizzo email: la verifica dell'indirizzo email è obbligatoria

## Contesto
TEST SUI SEGUENTI BROWSER: 
A) Google Chrome V. 79.0.3945.130 (Build ufficiale) (a 64 bit)
B) Internet Explorer V. 11.864.17763.0
C) Firefox V. 72.0.2 (64 bit)

**Comment by pdavide** [comment]
Vedi https://github.com/AgID/agid-forms-frontend/issues/63#issuecomment-582384917.

**Comment by eborzacchi** [comment]
Ho ripetuto il test con i browser indicati e ti confermo che i pulsanti non si abilitano per selezionare un file.

**Comment by eborzacchi** [comment]
Ho ripetuto il test (dopo aver effettuato la verifica della mail):
1. i pulsanti si sono abilitati
2. Invio effettuato
3. VERIFICA DELLE EMAIL INVIATE (vedi "**Comportamento atteso**" al punto 1)):
   3.1 **verifica invio email a protocollo@pec.agid.gov.it**: la mail non è stata ricevuta dal Protocollo, ma è stata deviata all'indirizzo di test "http://mail.form.agid.gov.it-131.1.241.146.nip.io/". Per poter effettuare un test completo è necessario che sia reale e che la mail arrivi effettivamente a protocollo@pec.agid.gov.it
   3.2 **verifica invio email a protocollo@pec.agid.gov.it deviata in "http://mail.form.agid.gov.it-131.1.241.146.nip.io/"**: ERRORE, la mail è arrivata ma senza gli allegati
   3.3 **verifica invio email al segnalante elenaborzacchi.almaviva@gmail.com deviata in "http://mail.form.agid.gov.it-131.1.241.146.nip.io/"**: ERRORE, la mail non è arrivata 
4. VERIFICA INVIO NOTIFICA DAL PROTOCOLLO AL SEGNALANTE (vedi "**Comportamento atteso**" al punto 2)):
   4.1 Il test sarà effettuato con l'Ufficio Protocollo, quando riceveranno la prima email dall'applicazione.

**Comment by pdavide** [comment]
@eborzacchi quella su cui stiamo facendo i test è un'istanza di staging le cui mail non sono realmente inviate.

Se non ci sono altri problemi rispetto alla procedura e manca solo la parte di invio mail provvedo ad abilitare un SMTP di test per verificare il tutto.

Gli allegati sono correttamente presenti, li trovi nella sezione "mime" del messaggio su http://mail.form.agid.gov.it-131.1.241.146.nip.io/.

**Comment by eborzacchi** [comment]
Grazie, ora gli allegati li ho visti, non me li aspettavo su un altro TAB :).
Mancherebbe solo l'invio della mail al segnalante (elenaborzacchi.almaviva@gmail.com), quella che sarebbe dovuta partire in contemporanea con quella verso il Protocollo.
Quella al segnalante non è arrivata su http://mail.form.agid.gov.it-131.1.241.146.nip.io/, è presente solo quella indirizzata al Protocollo.

**Comment by pdavide** [comment]
Da quello che ho letto nella mail in cui si parlava di `reply-to`, la mail al segnalante dovrebbe arrivare dal protocollo e non dall'applicazione.

**Comment by eborzacchi** [comment]
No, in realtà la prima email al segnalante deve essere inviata dal sistema, perché deve essere simultanea alla segnalazione fatta dall'utente (ART. 18 BIS LEGGE 241/1990). 
Successivamente, il segnalante riceverà (replay-to) una seconda email dal Protocollo, che gli comunicherà l'avvenuta protocollazione della segnalazione.

**Comment by pdavide** [comment]
Ok, dalla mail avevo capito che entrambe le mail (a ricezione e poi a protocollazione avvenuta) sarebbero state inviate dal protocollo.

Potresti scrivere qui il testo della mail da inviare al segnalante?

**Comment by eborzacchi** [comment]
Abbiamo condiviso la frase da inserire nella mail con Viviana, è un testo generico, che può essere utilizzato anche per il meccanismo di feedback:

Gentile cittadina/o,
la sua richiesta è stata inoltrata correttamente.
Grazie per averci contattato.

Restiamo in attesa di un tuo ok per poter ripetere il test, con l'invio effettivo della segnalazione all'ufficio Protocollo.

**Comment by pdavide** [comment]
@eborzacchi ho predisposto l'ambiente di test per l'invio di mail reali, ti mando i dettagli di accesso via mail.

Rispetto al testo delle mail forse è necessario usare un tono univoco per tutte. Considera che negli altri messaggi il tono è più diretto (uso del tu).

**Comment by eborzacchi** [comment]
@pdavide con Viviana abbiamo effettuato il test INVIO segnalazione e verificato con l'Ufficio Protocollo AGID per la procedura di attuazione, di seguito i risultati:
1.	La prima email al segnalante è arrivata correttamente al mittente
2.	Il protocollo ha ricevuto le email con i relativi allegati
3.	Protocollazione e invio atteso al “reply-to” impostato nel META: NON ha funzionato

Nel protocollare, la mail di notifica non è arrivata al segnalante (“reply-to”).
Abbiamo verificato i sorgenti delle email ricevute dal Protocollo (ti inoltro per email), e nell’header non abbiamo trovato configurato il “reply-to” con la mail del “segnalante”. 
Abbiamo trovato invece questa configurazione:
-	Email TEST UTENTE: In-Reply-To: <8443d78f-9f07-7e94-ca77-06d71628bc04@agid.gov.it>	
-	Email TEST UTENTE 2: In-Reply-To: <a7f89eff-1f95-f40a-a98a-99322919f24b@agid.gov.it>

**Comment by eborzacchi** [comment]
Test effettuati in base al nuovo "Comportamento atteso", modificato con la nuova soluzione concordata venerdì scorso in Call:

1.	TEST 01 
(https://form.agid.gov.it/form/procedura-attuazione/c38b99c0-7dc6-4fbb-9abf-db483ed19614/):
	-	INVIO segnalazione da form.agid.gov.it:
	A)	email di avvenuta ricezione al segnalante elenaborzacchi.almaviva@gmail.com : Mail inviata correttamente
	B)	email all'Ufficio Protocollo AGID con mittente elenaborzacchi.almaviva@gmail.com: NO, mail NON inviata al Protocollo

---------------------
2.	TEST 02 
(https://form.agid.gov.it/form/procedura-attuazione/c38b99c0-7dc6-4fbb-9abf-db483ed19614/):
	-INVIO segnalazione da form.agid.gov.it con una mail mittente PEC:
	A)	email di avvenuta ricezione al segnalante vivianadepaola@pec.it: Mail inviata con Anomalie, di seguito il contenuto della emal inviata dal sistema al segnalante PEC:
				[?10/?02/?2020 13:13]  De Paola Viviana:  
				Il giorno 10/02/2020 alle ore 13:09:14 (+0100) è stato ricevuto
				il messaggio "Form AGID ? codice di verifica email" proveniente da "no-reply@agid.gov.it"
				ed indirizzato a:
				vivianadepaola@pec.it
				Tali dati non sono stati certificati per il seguente errore:
				la firma digitale del messaggio non risulta attendibile
				Il messaggio originale è incluso in allegato. 
				Anomalia nel messaggio
	B)	email all'Ufficio Protocollo AGID con mittente vivianadepaola@pec.it: NO, mail NON inviata al Protocollo

**Comment by rscano** [comment]
> Gentile cittadina/o,

Non sarebbe meglio un generico "Gentile utente" ? vale con ambi i generi e soprattutto non discrimina chi non è cittadino.

**Comment by eborzacchi** [comment]
Abbiamo ripetuto i test che sono andati a buon fine.
Mentre per il messaggio contenuto nella mail, abbiamo dato lo stesso formato informale delle altre comunicazioni, come quella per il "codice di verifica email".
