### ISSUE TITLE
12 - Eliminazione errore W3C - Bad value for attribute src on element img: Must be non-empty

### ISSUE THREAD

**Issue by Git30072019** [AgID/agid-forms-frontend#81]
## Comportamento atteso
Eliminare errore W3C

## Comportamento attuale
Effettuando il test W3C (https://validator.w3.org/#validate_by_input) viene segnalato l'errore: Bad value for attribute src on element img: Must be non-empty

## Possibili soluzioni
Eliminare tutto o inserire l'attributo src <a href="/"><img src="" alt="">

**Comment by pdavide** [comment]
Fixed in 1357571ff046585cf20505b1f1460a37e586c16d.
