### ISSUE TITLE
16 - Errato contrasto di colore (1.4.3 Contrast - Minimum) su dicitura "Form" (breadcrumbs)

### ISSUE THREAD

**Issue by Git30072019** [AgID/agid-forms-frontend#85]
## Comportamento atteso
Ottenere un corretto contrasto (almeno 4.5:1)

## Comportamento attuale
Effettuando il test per il corretto contrasto di colore (CCA) il risultato non è sufficiente

## Possibili soluzioni
Modificare color: #5b6f82 con color: **#4D5E6F** in class .breadcrumb-container .breadcrumb .breadcrumb-item a {color: #4D5E6F; font-weight: 600;}

**Comment by pdavide** [comment]
Fixed in 772581e7fa632cc729f63ed30ab6ee1a7edffa3d.
